"""Add status column to habitlist table

Revision ID: 114a13559369
Revises: 17380fbb8fc2
Create Date: 2024-11-13 18:16:41.581977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '114a13559369'
down_revision = '17380fbb8fc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habitlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habitlist', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
