"""Removed status from Habit model

Revision ID: 43eeea02293c
Revises: 114a13559369
Create Date: 2024-11-14 16:42:04.223477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43eeea02293c'
down_revision = '114a13559369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
